version: "3"

services:
  pgdb:
    image: postgres:16.2
    ports:
      - "54320:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./uploads_pics:/uploads_pics/
    networks:
      - app-network

volumes:
  pg_data:
  nginx_data:

networks:
  app-network:
    driver: bridge