openapi: 3.0.0
info:
  title: Летняя Практика
  version: 1.0.0
  description: API сервиса контроля и анализа данных с использованием модели нейронной сети

paths:

  /login/:
    post:
      summary: Аутентификация пользователя
      description: Логин пользователя по username и паролю.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: Успешная аутентификация
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  user_data:
                    type: object
                    properties:
                      username:
                        type: string
                        example: username
                      name:
                        type: string
                        example: John
                      last_name:
                        type: string
                        example: Doe
                      email:
                        type: string
                        example: user@example.com
        '400':
          description: Неверные учетные данные
        '500':
          description: Внутренняя ошибка сервера
        '401':
          description: Пользователь уже аутентифицирован

  /upload:
    post:
      summary: Обработка и загрузка изображения
      description: Генерация изображения или загрузка пользовательского изображения для обработки.
      parameters:
        - in: query
          name: flag
          schema:
            type: boolean
          required: false
          description: Флаг для указания, генерировать ли изображение на сервере.
        - in: query
          name: end_date
          schema:
            type: string
            format: date-time
          required: false
          description: Конечная дата для генерации изображения.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                img:
                  type: string
                  format: binary
                  description: Изображение для обработки, если flag=false.
      responses:
        '200':
          description: Успешная обработка изображения
        '400':
          description: Не удалось загрузить изображение
        '500':
          description: Внутренняя ошибка сервера

  /logout/:
    post:
      summary: Выход пользователя из системы
      description: Завершение сеанса пользователя.
      responses:
        '200':
          description: Пользователь успешно вышел из системы

  /get_modified/:
    get:
      summary: Получение модифицированных данных
      description: Возвращает список модифицированных данных за указанный период.
      parameters:
        - in: query
          name: start_date
          schema:
            type: string
            format: date-time
          required: true
          description: Начальная дата выборки данных.
        - in: query
          name: end_date
          schema:
            type: string
            format: date-time
          required: true
          description: Конечная дата выборки данных.
      responses:
        '200':
          description: Успешный ответ с данными
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  data:
                    type: array
                    items:
                      type: object
        '400':
          description: Параметры start_date и end_date обязательны
        '500':
          description: Внутренняя ошибка сервера

  /get_aggregate/:
    get:
      summary: Получение агрегированных данных
      description: Возвращает список агрегированных данных за указанный период.
      parameters:
        - in: query
          name: start_date
          schema:
            type: string
            format: date-time
          required: true
          description: Начальная дата выборки данных.
        - in: query
          name: end_date
          schema:
            type: string
            format: date-time
          required: true
          description: Конечная дата выборки данных.
      responses:
        '200':
          description: Успешный ответ с данными
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  data:
                    type: array
                    items:
                      type: object
        '400':
          description: Параметры start_date и end_date обязательны
        '500':
          description: Внутренняя ошибка сервера

  /get_initial/:
    get:
      summary: Получение исходных данных
      description: Возвращает список исходных данных за указанный период.
      parameters:
        - in: query
          name: start_date
          schema:
            type: string
            format: date-time
          required: true
          description: Начальная дата выборки данных.
        - in: query
          name: end_date
          schema:
            type: string
            format: date-time
          required: true
          description: Конечная дата выборки данных.
      responses:
        '200':
          description: Успешный ответ с данными
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  data:
                    type: array
                    items:
                      type: object
        '400':
          description: Параметры start_date и end_date обязательны
        '500':
          description: Внутренняя ошибка сервера
