# Generated by Django 5.0.7 on 2024-08-05 16:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=15, max_digits=20), size=None)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='modifieddata',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=15, max_digits=20), size=None),
        ),
    ]
