name: "resnet18"
platform: "onnxruntime_onnx"
max_batch_size: 32
input [
    {
        name: "keras_tensor"
        data_type: TYPE_FP32
        dims: [128, 336, 1]
    }
]
output [
    {
        name: "output_tensor"
        data_type: TYPE_FP32
        dims: [64]
    }
]

dynamic_batching { }